baseurl = "https://elevateheatingllc.com/"
contentDir = "content"
languageCode = "en-us"
languageLang = "en"
title = "Elevate Heating & Cooling"
copyright = "Copyright &copy; {year} Elevate Heating & Cooling, LLC, all rights reserved."
permalinks = "/:slug/"

preserveTaxonomyNames = false

canonifyURLs = true

enableRobotsTXT = true # generate robots.txt

[params]
disallow_search_engines = false # set robots.txt to disallow everything

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
#disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

disableKinds = ["taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

[[menu.main]]
name = "Funace Repair"
weight = 1
identifier = "Funace Repair & Maintenance"
url = "furnace-repair-and-maintenance"

[[menu.main]]
name = "AC Repair"
weight = 2
identifier = "AC Repair & Maintenance"
url = "ac-repair-and-maintenance"

[[menu.main]]
name = "Electric Fan Coil Tune Up"
weight = 3
identifier = "Electric Fan Coil Tune Up"
url = "electric-fan-coil-tune-up"

[[menu.main]]
name = "Ductless/Mini-Split Installations"
weight = 4
identifier = "Ductless/Mini-Split Installations"
url = "ductless-mini-split-installations"

[[menu.main]]
name = "Reviews"
weight = 4
identifier = "Reviews"
url = "reviews"

[[menu.main]]
name = "Contact us"
weight = 5
identifier = "Contact Us"
url = "contact-us"