baseurl = "https://elevateheating.com"
contentDir = "content"
languageCode = "en-us"
languageLang = "en"
title = "Elevate Heating & Cooling"
copyright = "Copyright &copy; {year} Elevate Heating & Cooling, Inc, all rights reserved."
permalinks = "/:slug/"

preserveTaxonomyNames = false

canonifyURLs = true

enableRobotsTXT = true # generate robots.txt

[params]
disallow_search_engines = false # set robots.txt to disallow everything

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
#disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

disableKinds = ["taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

[params.logo]
mobile = "images/logo-sm.png"
mobile_height = "96"
mobile_width = "275"
alt = "Elevate Heating & Cooling, Inc"

[[menu.main]]
name = "Heating"
weight = 1
identifier = "Heating"
url = "/heating/"

[[menu.main]]
name = "Heating Installation"
weight = 2
identifier = "Heating Installation"
url = "heating-installation/"
parent = "Heating"

[[menu.main]]
name = "Heat Pumps"
weight = 3
identifier = "Heat Pumps"
url = "heat-pumps/"
parent = "Heating"

[[menu.main]]
name = "Heating Repair"
weight = 4
identifier = "Heating Repair"
url = "heating-repair/"
parent = "Heating"

[[menu.main]]
name = "Furnace Repair"
weight = 5
identifier = "Furnace Repair & Maintenance"
url = "furnace-repair-and-maintenance/"
parent = "Heating"

[[menu.main]]
name = "Heat Pump Tune-Up"
weight = 6
identifier = "Heat Pump Tune-Up"
url = "heat-pump-tune-up/"
parent = "Heating"

[[menu.main]]
name = "Cooling"
weight = 7
identifier = "Cooling"
url = "/air-conditioning/"

[[menu.main]]
name = "AC Repair"
weight = 8
identifier = "AC Repair & Maintenance"
url = "ac-repair-and-maintenance/"
parent = "Cooling"

[[menu.main]]
name = "AC Installation"
weight = 9
identifier = "AC Installation"
url = "ac-installation/"
parent = "Cooling"

[[menu.main]]
name = "Ductless/Mini-Split Installations"
weight = 10
identifier = "Ductless/Mini-Split Installations"
url = "/ductless-mini-split-installations/"
parent = "Cooling"

[[menu.main]]
name = "Reviews"
weight = 11
identifier = "Reviews"
url = "/reviews/"

[[menu.main]]
name = "Contact us"
weight = 12
identifier = "Contact Us"
url = "/contact-us/"