[build]
publish = "public"
command = "hugo --gc --minify --disableKinds=taxonomy,taxonomyTerm"

[context.production.environment]
HUGO_VERSION = "0.129.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.129.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.129.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.129.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
	from = "http://www.elevateheatingllc.com/*"
	to = "https://elevateheating.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://www.elevateheatingllc.com/*"
	to = "https://elevateheating.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "http://elevateheatingllc.com/*"
	to = "https://elevateheating.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://elevateheatingllc.com/*"
	to = "https://elevateheating.com/:splat"
	status = 301
	force = true

[[redirects]]
  from = "/electric-fan-coil-tune-up"
  to = "/heat-pump-tune-up"
  status = 301

[[redirects]]
	from = "/heating-service"
	to = "/heating"
	status = 301

[[redirects]]
	from = "/heating-service/heat-pumps"
	to = "/heat-pumps"
	status = 301