[build.environment]
HUGO_VERSION = "0.129.0"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
	from = "http://www.elevateheatingllc.com/*"
	to = "https://elevateheating.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://www.elevateheatingllc.com/*"
	to = "https://elevateheating.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "http://elevateheatingllc.com/*"
	to = "https://elevateheating.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://elevateheatingllc.com/*"
	to = "https://elevateheating.com/:splat"
	status = 301
	force = true

[[redirects]]
  from = "/electric-fan-coil-tune-up"
  to = "/heat-pump-tune-up"
  status = 301

[[redirects]]
	from = "/heating-service"
	to = "/heating"
	status = 301

[[redirects]]
	from = "/heating-service/heat-pumps"
	to = "/heat-pumps"
	status = 301